### ISSUE TITLE
Join procedure fails after changing the AppKey

### ISSUE THREAD

**Issue by PG430** [STMicroelectronics/STM32CubeWL#37] opened 2022-04-01 03:29 UTC
Hi,

During the testing we have found something interesting. During the Join procedure device is using Network key instead of AppKey
As per the LoRA spec device must use AppKey to generate message integrity code(MIC). 

![image](https://user-images.githubusercontent.com/55126032/161189208-9810b3d6-9e62-49f9-9112-fad811bf839d.png)

![image](https://user-images.githubusercontent.com/55126032/161189652-c3480a25-ddfc-4ff8-82ab-209c8ec4b401.png)

we have found this when we have change the appkey of device and used same in server as appkey, after the changes we are seeing MIC failure in join request.
Please help to understand why Network Key is in use for join procedure?

**Comment by ASELSTM** [comment] 2022-04-11 12:05
ST Internal Reference: 126216

**Comment by PG430** [comment] 2022-04-14 05:54
Any comment?

**Comment by PG430** [comment] 2022-05-02 11:34
@ASELSTM any update? anything that you can share will be helpful

**Comment by PG430** [comment] 2022-05-04 05:27
@ASELSTM   Please share any available update regarding this concern.

**Comment by PG430** [comment] 2022-06-15 10:07
@ALABSTM can you share any updates on this issue?

**Comment by PG430** [comment] 2022-07-18 12:53
@ASELSTM can you share any updates on this issue?

**Comment by ALABSTM** [comment] 2022-12-08 14:28
Duplicate of #24.

**Closed** 2022-12-08 15:05 UTC
Labels: duplicate, question, mw, internal bug tracker, lorawan

**Comment by PG430** [comment] 2022-12-09 04:53
@ALABSTM Thank you for the detail clarification.
